### ISSUE TITLE
Login Screen

### ISSUE THREAD

**Issue by chenbachar** [chenbachar/daycare#1]
- [x] Add Logo
- [x] Clicking outside of EditText closes keyboard
- [x] Make register looks like a link
- [x] On "register" click: open WebView to display registration address

**Comment by chenbachar** [comment]
1. Added Logo.
2. Made "Registration" looks like a link.
3. Registration opens WebView to register.
4. Clicking outside of EditText closes keyboard
