### ISSUE TITLE
Contact List Activity

### ISSUE THREAD

**Issue by chenbachar** [chenbachar/daycare#14]
- [x] Create a list view (Maybe with RecyclerView)
- [x] Populate a sample list / Mock Objects _**(prototype purpose)**_
- [x] Research about onClickListener with Adapter
- [x] Long click opens dialog to dial or sms
- [x] When dialog opens - First option calls the person
- [x] When dialog opens - Second option send an sms

**Comment by chenbachar** [comment]
### Use intents to make a phone call to the desired number:

first add to AndroidManifest:
`
<uses-permission android:name="android.permission.CALL_PHONE"/>
`

Then, when click is done:

`Intent callIntent = new Intent(Intent.ACTION_CALL);`
`callIntent.setData(Uri.parse("tel:123456789"));`
`startActivity(callIntent);`

### Use intents to send an SMS:

add to Manifest:
`<uses-permission android:name="android.permission.SEND_SMS" />`

Then onClick use:

`Intent sendIntent = new Intent(Intent.ACTION_VIEW);`
`sendIntent.setData(Uri.parse("sms:123456789"));`
`startActivity(sendIntent);`
