### ISSUE TITLE
Classes ("Hoogim")

### ISSUE THREAD

**Issue by chenbachar** [chenbachar/daycare#19]
- [x] Create one activity
- [x] Swipe between fragments
- [x] Add 'info' icon
- [x] set onClick for info
- [x] When click on info open dialog with info about the selected class
- [x] Add pictures for chosen classes
- [x] Add mock objects including picutres, info and title
