### ISSUE TITLE
Calendar Activity

### ISSUE THREAD

**Issue by chenbachar** [chenbachar/daycare#2]
## To do:
- [x] Create a calendar at the top 
- [x] Create a list view to show events
- [x] For every occupied date, change background color
- [x] Design calendar
