### ISSUE TITLE
Updates (from daycare) Activity

### ISSUE THREAD

**Issue by chenbachar** [chenbachar/daycare#6]
## To do:
- [x] Make a card view
- [x] Swipe left (or right) cards to delete
- [x] 1st line is the message; 2nd line is date sent
- [x] Add 'Show Help' to actionbar
