### ISSUE TITLE
Private Messages Activity (NOT A CHAT!)

### ISSUE THREAD

**Issue by chenbachar** [chenbachar/daycare#7]
- [x] Add CardView for messages
- [x] Each card should have text
- [x] Each card should have a date and time
- [x] Each card should have a special 'label' that indicates the message type ('Request', etc...)
